### ISSUE TITLE
Unable to build minimalPkg

### ISSUE THREAD

**Issue by arcao** [SynologyOpenSource/minimalPkg#2]
Hi,

I am trying to build this example package by documentation located at https://developer.synology.com/developer-guide/index.html.

I prepared my environment as is there described:
```
mkdir -p /toolkit
cd /toolkit
git clone https://github.com/SynologyOpenSource/pkgscripts-ng.git
cd /toolkit/pkgscripts-ng/
./EnvDeploy -v 6.0 -p bromolow

mkdir -p /toolkit/build_env/ds.bromolow-6.0/root/.gnupg/
cp ~/.gnupg/* /toolkit/build_env/ds.bromolow-6.0/root/.gnupg/
```

Then downloaded minimalPkg:
```
cd /toolkit
git clone https://github.com/SynologyOpenSource/minimalPkg.git
```

A builded with:
```
pkgscripts-ng/PkgCreate.py -p bromolow -c minimalPkg
```

Unfortunately this results with error:
```
============================================================
                   Parse argument result                    
------------------------------------------------------------
package      : minimalPkg
env_section  : default
branch       : master
only_install : False
collect      : True
update       : True
build_opt    : 
suffix       : 
sdk_ver      : 6.0
install_opt  : 
dep_level    : 1
install      : True
build        : True
link         : True
env_version  : None
sign         : True
print_log    : False

Traceback (most recent call last):
  File "pkgscripts-ng/PkgCreate.py", line 722, in <module>
    main(sys.argv[1:])
  File "pkgscripts-ng/PkgCreate.py", line 690, in main
    worker_factory = WorkerFactory(args)
  File "pkgscripts-ng/PkgCreate.py", line 136, in __init__
    args.branch, args.suffix)
  File "pkgscripts-ng/PkgCreate.py", line 573, in __init__
    self.dict_env = getBaseEnvironment(package, env_section, version)
  File "pkgscripts-ng/PkgCreate.py", line 682, in getBaseEnvironment
    depends = config_parser.DependsParser(BuildEnv.Project(proj).depends_script)
  File "/toolkit/pkgscripts-ng/include/python/config_parser.py", line 20, in __init__
    raise ConfigNotFoundError(config)
config_parser.ConfigNotFoundError  
```

Any idea what I am doing wrong?

**Comment by SynologyOpenSource** [comment]
Hi Arcao,

The minimalPkg must under **source/** folder. You can see https://developer.synology.com/developer-guide/create_package/build_and_create_package.html _Source Code Layout_ section for more information.

Thanks.

**Comment by arcao** [comment]
Thanks! It works!

**Comment by tacc716** [comment]
when i try pkgscripts-ng/PkgCreate.py -p bromolow -c minimalPkg it throw 
`============================================================
                   Parse argument result                    
------------------------------------------------------------
link         : True
build        : True
sign         : True
dep_level    : 1
update       : True
install      : True
package      : minimalPkg
build_opt    : 
collect      : True
only_install : False
env_version  : None
install_opt  : 
sdk_ver      : 6.0
print_log    : False
branch       : master
env_section  : default
suffix       : 


PkgCreateError:
No platform found!

[ERROR] pkgscripts-ng/PkgCreate.py -p bromolow -c minimalPkg failed!
`

Any solution ?

**Comment by SynologyOpenSource** [comment]
Hi @tacc716,

Thanks for your reply. Please check:
1. `build_env/ds.bromolow-6.1` exists.
2. `source/minimalPkg/SynoBuildConf/depends` has version `all="6.1"`

PkgCreate.py will find the target platform according to the depends version. If `build_env/ds.bromolow-6.1` not exists, please follow [pkgscripts-ng](https://github.com/SynologyOpenSource/pkgscripts-ng) to set up the environment or adjust the depends version.

Thanks.
